server:
  port: 8088
#  context-path: springboot
spring:
    freemarker:
        allow-request-override: false
        allow-session-override: false
        cache: true
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        prefer-file-system-access: true
        suffix: .ftl
        template-loader-path: classpath:/templates/
    datasource:
        baseName: springbootwebapp
        url: jdbc:mysql://localhost:3306/springbootdb
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
        #使用druid数据源
#        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 30
#        initialSize: 2
#        maxWait: 5000
#        minIdle: 2
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 30000
#        testWhileIdle: false
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
#    mybatis:
#        mapperLocations: classpath:mybatis/mapper/*.xml
#        config: classpath:mybatis/mybatis-config.xml
    output:
      ansi:
        enabled: always
    http:
      multipart:
        enabled: true
        max-file-size: 100Mb
        max-request-size: 100Mb
        location: D:\upload
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    aop:
      #使用cglib来实现aop
      proxy-target-class: true
    profiles:
      active: test #表示测试环境 @Profile("prod") 注解在接口实现类上
logging:
  config: classpath:config/logback.xml
# 更多数据源
custom:
  datasource:
    names: ds1,ds2
    ds1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springbootdb
      username: root
      password: admin
    ds2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springbootdb
      username: root
      password: admin